[package]
name = "toy_pool"
version = "0.1.1"
edition = "2018"
description = "Pool with reference-counted items"
license = "MIT"

[dependencies]
derivative = "2.2.0"
igri = { path = "../igri/igri", version = "0.1.3", optional = true }
